[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn -w 1 --threads 1 -k gthread -b 0.0.0.0:$PORT web_interface:app --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 300

# Note: Le volume persistant doit être créé manuellement dans Railway Dashboard
# Mount Path: /data, Size: 1GB minimum

