name: Deploy to Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway (CI)
        run: |
          # Auth non-interactive via variable d'environnement (RAILWAY_TOKEN)
          # Ecrire railway.json avec le projectId pour éviter link interactif
          echo "{\n  \"projectId\": \"$RAILWAY_PROJECT_ID\"\n}" > railway.json
          cat railway.json
          railway up --ci --service web
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}


